### ISSUE TITLE
Some test failures

### ISSUE THREAD

**Issue by utkarsh2102** [chef/ffi-yajl#106]
Hi,

Whilst building 2.3.1 against Ruby 2.7, there are some test failures as follows:
```
Failures:

  1) FFI_Yajl::MapLibraryName #expanded_library_names maps mswin correctly
     Failure/Error: expect(Test.send(:expanded_library_names)).to eq(expanded_library_names)

     RuntimeError:
       CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true
     # ./spec/ffi_yajl/map_library_name_spec.rb:67:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NameError:
     #   uninitialized constant RSpec::Support::Differ
     #   ./spec/ffi_yajl/map_library_name_spec.rb:67:in `block (4 levels) in <top (required)>'

  2) FFI_Yajl::MapLibraryName #expanded_library_names maps solaris2 correctly
     Failure/Error: expect(Test.send(:expanded_library_names)).to eq(expanded_library_names)

     NameError:
       uninitialized constant RSpec::Support::Differ
     # ./spec/ffi_yajl/map_library_name_spec.rb:67:in `block (4 levels) in <top (required)>'

  3) FFI_Yajl::MapLibraryName #expanded_library_names maps aix correctly
     Failure/Error: expect(Test.send(:expanded_library_names)).to eq(expanded_library_names)

     NameError:
       uninitialized constant RSpec::Support::Differ
     # ./spec/ffi_yajl/map_library_name_spec.rb:67:in `block (4 levels) in <top (required)>'

Finished in 0.7233 seconds (files took 0.26147 seconds to load)
448 examples, 3 failures, 18 pending

Failed examples:

rspec ./spec/ffi_yajl/map_library_name_spec.rb[1:6:1] # FFI_Yajl::MapLibraryName #expanded_library_names maps mswin correctly
rspec ./spec/ffi_yajl/map_library_name_spec.rb[1:18:1] # FFI_Yajl::MapLibraryName #expanded_library_names maps solaris2 correctly
rspec ./spec/ffi_yajl/map_library_name_spec.rb[1:26:1] # FFI_Yajl::MapLibraryName #expanded_library_names maps aix correctly

Randomized with seed 65442
```

Any clue about the fix?

**Comment by phiggins** [comment]
Hi,

I can't repro this by building on master with ruby 2.7.1. Since this project does not reference `RSpec::Support::Differ` directly, it seems like the problem might be in your development environment, specifically something having to do with rspec. Can you give the exact commands you're running with all of the output generated?
