### ISSUE TITLE
cygwin impossible to use

### ISSUE THREAD

**Issue by iongion** [chef/ffi-yajl#36]
After installing:

```
$ ruby --version
ruby 1.9.3p484 (2013-11-22) [x86_64-cygwin]
$ gem install ffi-yajl
Building native extensions.  This could take a while...
Successfully installed ffi-yajl-1.3.1
1 gem installed
Installing ri documentation for ffi-yajl-1.3.1...
Installing RDoc documentation for ffi-yajl-1.3.1...
```

The gem compiles perfectly but anything using it throws this:

```
/usr/lib/ruby/gems/1.9.1/gems/ffi-yajl-1.3.1/lib/ffi_yajl/ext.rb:38:in `initialize': No such file or directory (DL::DLError)
        from /usr/lib/ruby/gems/1.9.1/gems/ffi-yajl-1.3.1/lib/ffi_yajl/ext.rb:38:in `dlopen'
        from /usr/lib/ruby/gems/1.9.1/gems/ffi-yajl-1.3.1/lib/ffi_yajl/ext.rb:38:in `try_dl_dlopen'
        from /usr/lib/ruby/gems/1.9.1/gems/ffi-yajl-1.3.1/lib/ffi_yajl/ext.rb:63:in `<module:FFI_Yajl>'
        from /usr/lib/ruby/gems/1.9.1/gems/ffi-yajl-1.3.1/lib/ffi_yajl/ext.rb:8:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/gems/1.9.1/gems/ffi-yajl-1.3.1/lib/ffi_yajl.rb:28:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/json_compat.rb:20:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/data_bag.rb:26:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/data_bag_item.rb:26:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/encrypted_data_bag_item.rb:20:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
```

it dies at: ```require 'chef/encrypted_data_bag_item'```

**Comment by lamont-granquist** [comment]
Probably fixed by #43
